### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [McDiod/CO_Woodpecker.tem_vinjesvingenc#1]
- [x] Funkgeräte für Loadouts
- [x] Ausrüstung bei FOB
- [x] Introsong Ende
- [x] Tankstellenscript
- [x] Tankstelleninteraction
- [x] wegfahrendes Auto bei FOB
- [x] Zivilisten
- [x] Ende vom Song lauter
- [x] dingens vom Helipad löschen
- [x] Missionsende
- [x] zus. Loadouts für Opfor
- [x] Gegner platzieren
